version: '3.7'
services:
  api:
    build:
      context: .
      target: development
    image: lanchonete-pedido-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db-pedido-lanchonete
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - lanchonete-pedido-network
  db-pedido-lanchonete:
    image: postgres
    container_name: db-pedido-lanchonete
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - lanchonete-pedido-network
  db-pedido-lanchonete-test:
    image: postgres
    container_name: db-pedido-lanchonete-test
    env_file:
      - .env.test
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    networks:
      - lanchonete-pedido-network
volumes:
  postgres_data:
  postgres_data_test:
networks:
  lanchonete-pedido-network:
    name: lanchonete-pedido-network
