version: '3.7'
services:
  api:
    build:
      context: .
      target: development
    image: pedido-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db-pedido
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - pedido-network
  db-pedido:
    image: postgres
    container_name: db-pedido
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_pedido:/var/lib/postgresql/data/
    networks:
      - pedido-network
  db-pedido-test:
    image: postgres
    container_name: db-pedido-test
    env_file:
      - .env.test
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - pedido_db_test:/var/lib/postgresql/data/
    networks:
      - pedido-network
volumes:
  postgres_pedido:
  pedido_db_test:
networks:
  pedido-network:
    name: pedido-network
