apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pedido
  template:
    metadata:
      labels:
        app: postgres-pedido
    spec:
      containers:
      - name: postgres-pedido
        image: postgres
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.5"
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-pedido-secrets
                key: postgres_db
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-pedido-secrets
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-pedido-secrets
                key: postgres_password
