apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete-pedido
  template:
    metadata:
      labels:
        app: lanchonete-pedido
    spec:
      containers:
        - name: projeto-lanchonete-pedido
          image: rickwalking/lanchonete-pedido:latest
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: database_url
