apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  database_url: cG9zdGdyZXNxbDovL2RhdGFiYXNldGVzdGU6cGFzc3dvcmRAdGVycmFmb3JtLWRhdGFiYXNlLXRlc3QuY2J1ZXp3ZHlxbHdqLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2xhbmNob25ldGVfZGI=
