apiVersion: v1
kind: Service
metadata:
  name: lanchonete-pedido
  namespace: microservices
spec:
  selector:
    app: lanchonete-pedido
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
